### ISSUE TITLE
你这项目在android studio 上怎么运行呢？

### ISSUE THREAD

**Issue by WM520** [amazingyyc/DeepRed#2]

**Comment by amazingyyc** [comment]
打开Android Studio->导入项目->点击run

**Comment by WM520** [comment]
怎么报错呢，现在还能跑吗，我Android Studio是最新的

**Comment by WM520** [comment]
我比较菜，你项目里面没有gradle 咋跑呢

**Comment by WM520** [comment]
比较急，项目需要开发livephoto这个功能，感谢！

**Comment by amazingyyc** [comment]
这个代码几年前的代码啦，你尝试一下 新建一个项目然后添加源代码的方式试试

**Comment by WM520** [comment]
目录结构是不是也变了

**Comment by amazingyyc** [comment]
目录结构保持原来的结构，记得编译c文件

**Comment by WM520** [comment]
c文件是怎么编译呢，尴尬了，我没弄过。。

**Comment by amazingyyc** [comment]
有些好的mk文件，去android develop网站看一下怎么android studio怎么编译mk文件

**Comment by WM520** [comment]
你项目里，.so已经生成了，我还需要编译jni吗

**Comment by amazingyyc** [comment]
需要的 .so是ffmpeg的执行文件，你需要编译DeepRed/jni/recorder/中的c++文件
对应的mk文件在DeepRed/jni/中

**Comment by WM520** [comment]
恩恩，你这拍摄的livephoto能连续拍摄吗，和华为自带的相机的动图图片模式拍摄一样不

**Comment by WM520** [comment]
我想做这个livephoto功能，能做出保存成jpg的图片吗

**Comment by amazingyyc** [comment]
你所谓的连续拍摄是指什么？
其实这个livephoto很简单，就是在你拍摄按钮按下的时候存储一段前后的视频而已

**Comment by amazingyyc** [comment]
jpg是图片 你只需要在点击按钮之后存储一张图片即可

**Comment by WM520** [comment]
就是和正常拍照一样，不需要拍摄过后等一段时间才能继续拍摄

**Comment by amazingyyc** [comment]
无法做到，因为是软件编码速度很慢，当你连续点击按钮的时候有可能之前的视频还没编码完成。

**Comment by WM520** [comment]
你还做安卓不，现在mate10，mate9 都能和苹果一样，连续拍摄livephoto

**Comment by amazingyyc** [comment]
猜测两种可能
1:手机很快，即使软件编码也可以实时拍摄。
2:硬件编码视频。
你可以用mate手机试试软件编码的速度。

算是在做Android吧。。

**Comment by WM520** [comment]
https://github.com/hwpjiayou/cameralive/ 这个人和你的项目一样。。

**Comment by amazingyyc** [comment]
应该是fork的

**Comment by WM520** [comment]
亲你qq多少能告知吗，我实在搞不定，有几个问题请教

**Comment by amazingyyc** [comment]
1219186770
